;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 7
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env0,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $06
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $23
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $33
	.word @env1,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ca,$c5,$c0,$00,$03
@env2:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c0,$00,$07
@env3:
	.byte $cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$07


@song0ch0:
	.byte $fb,$0c
@song0ch0loop:
@ref0:
	.byte $82,$40,$83,$00,$59,$00,$4e,$8d,$00
@ref1:
	.byte $4a,$83,$00,$59,$00,$40,$8d,$00
@ref2:
	.byte $40,$83,$00,$4a,$83,$00,$59,$00,$5c,$85,$00
@ref3:
	.byte $58,$83,$00,$4e,$83,$00,$4a,$8b,$00
@ref4:
	.byte $40,$83,$00,$59,$00,$4e,$8d,$00
	.byte $ff,$08
	.word @ref1
	.byte $ff,$0b
	.word @ref2
	.byte $ff,$09
	.word @ref3
@ref8:
	.byte $9f
@ref9:
	.byte $9f
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref10:
	.byte $9f
@ref11:
	.byte $9f
@ref12:
	.byte $9f
@ref13:
	.byte $9f
@ref14:
	.byte $9f
@ref15:
	.byte $9f
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
@ref19:
	.byte $9f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref20:
	.byte $9f
@ref21:
	.byte $9f
@ref22:
	.byte $9f
@ref23:
	.byte $9f
@ref24:
	.byte $9f
@ref25:
	.byte $9f
@ref26:
	.byte $9f
@ref27:
	.byte $9f
@ref28:
	.byte $9f
@ref29:
	.byte $9f
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref30:
	.byte $81,$80,$14,$14,$00,$14,$14,$14,$00,$14,$15,$00,$14,$15,$00
@ref31:
	.byte $81,$14,$14,$00,$14,$14,$14,$00,$14,$15,$00,$14,$15,$00
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref40:
	.byte $9f
@ref41:
	.byte $9f
@ref42:
	.byte $9f
@ref43:
	.byte $9f
@ref44:
	.byte $9f
@ref45:
	.byte $9f
@ref46:
	.byte $9f
@ref47:
	.byte $9f
@ref48:
	.byte $9f
@ref49:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$07
@song1ch0loop:
@ref50:
	.byte $82,$4a,$83,$00,$52,$83,$00,$40,$83,$00,$52,$83,$00
@ref51:
	.byte $4a,$83,$00,$52,$83,$00,$40,$83,$00,$52,$83,$00
	.byte $ff,$0c
	.word @ref51
	.byte $ff,$0c
	.word @ref51
	.byte $ff,$0c
	.word @ref51
@ref55:
	.byte $4e,$83,$00,$58,$83,$00,$40,$83,$00,$58,$83,$00
	.byte $ff,$0c
	.word @ref51
@ref57:
	.byte $3c,$83,$00,$4a,$83,$00,$4e,$83,$00,$58,$83,$00
	.byte $ff,$0c
	.word @ref51
	.byte $ff,$0c
	.word @ref57
@ref60:
	.byte $3c,$85,$4a,$85,$40,$85,$48,$85
@ref61:
	.byte $4a,$9d
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref62:
	.byte $9f
@ref63:
	.byte $9f
@ref64:
	.byte $9f
@ref65:
	.byte $9f
@ref66:
	.byte $9f
@ref67:
	.byte $9f
@ref68:
	.byte $9f
@ref69:
	.byte $9f
@ref70:
	.byte $9f
@ref71:
	.byte $9f
@ref72:
	.byte $9f
@ref73:
	.byte $9f
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref74:
	.byte $9f
@ref75:
	.byte $9f
@ref76:
	.byte $9f
@ref77:
	.byte $9f
@ref78:
	.byte $84,$52,$00,$83,$52,$00,$54,$00,$58,$00,$83,$52,$00,$83
@ref79:
	.byte $54,$00,$83,$54,$00,$58,$00,$4e,$00,$83,$40,$00,$83
@ref80:
	.byte $52,$00,$83,$52,$00,$54,$00,$58,$00,$83,$62,$00,$83
@ref81:
	.byte $5c,$8b,$00,$58,$00,$8b
@ref82:
	.byte $52,$00,$83,$52,$00,$54,$00,$58,$00,$83,$52,$00,$83
	.byte $ff,$0d
	.word @ref79
@ref84:
	.byte $52,$00,$83,$52,$00,$54,$00,$4e,$00,$83,$48,$00,$83
@ref85:
	.byte $4a,$8b,$00,$8f
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref86:
	.byte $9f
@ref87:
	.byte $9f
@ref88:
	.byte $9f
@ref89:
	.byte $9f
@ref90:
	.byte $9f
@ref91:
	.byte $9f
@ref92:
	.byte $9f
@ref93:
	.byte $9f
@ref94:
	.byte $9f
@ref95:
	.byte $9f
@ref96:
	.byte $9f
@ref97:
	.byte $9f
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref98:
	.byte $9f
@ref99:
	.byte $9f
@ref100:
	.byte $9f
@ref101:
	.byte $9f
@ref102:
	.byte $9f
@ref103:
	.byte $9f
@ref104:
	.byte $9f
@ref105:
	.byte $9f
@ref106:
	.byte $9f
@ref107:
	.byte $9f
@ref108:
	.byte $9f
@ref109:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$09
@song2ch0loop:
@ref110:
	.byte $86,$56,$00,$4c,$00,$56,$00,$4c,$00,$56,$00,$4c,$00
@ref111:
	.byte $56,$00,$4c,$00,$56,$00,$4c,$00,$56,$00,$4c,$00
@ref112:
	.byte $48,$00,$44,$00,$4c,$83,$00,$44,$00,$48,$00
@ref113:
	.byte $52,$00,$50,$00,$52,$00,$56,$00,$50,$00,$48,$00
@ref114:
	.byte $56,$00,$48,$00,$56,$00,$48,$00,$56,$00,$48,$00
@ref115:
	.byte $56,$00,$46,$00,$56,$00,$46,$00,$58,$83,$00
@ref116:
	.byte $56,$00,$4e,$00,$56,$00,$4e,$00,$52,$00,$56,$00
@ref117:
	.byte $52,$83,$00,$4e,$83,$00,$4a,$83,$00
	.byte $ff,$0c
	.word @ref111
	.byte $ff,$0c
	.word @ref111
	.byte $ff,$0b
	.word @ref112
	.byte $ff,$0c
	.word @ref113
	.byte $ff,$0c
	.word @ref114
	.byte $ff,$0b
	.word @ref115
	.byte $ff,$0c
	.word @ref116
	.byte $ff,$09
	.word @ref117
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref126:
	.byte $86,$3e,$00,$44,$00,$4c,$00,$44,$00,$4c,$00,$44,$00
@ref127:
	.byte $3e,$00,$44,$00,$4c,$00,$44,$00,$4c,$00,$44,$00
@ref128:
	.byte $36,$00,$3e,$00,$44,$00,$3e,$00,$36,$00,$3e,$00
@ref129:
	.byte $36,$00,$3e,$00,$44,$00,$3e,$83,$00,$36,$00
@ref130:
	.byte $30,$00,$36,$00,$3e,$00,$36,$00,$3e,$00,$36,$00
@ref131:
	.byte $30,$00,$34,$00,$3e,$00,$34,$00,$3e,$00,$34,$00
	.byte $ff,$0c
	.word @ref127
@ref133:
	.byte $3a,$00,$40,$00,$4c,$00,$40,$00,$4c,$00,$40,$00
	.byte $ff,$0c
	.word @ref127
	.byte $ff,$0c
	.word @ref127
	.byte $ff,$0c
	.word @ref128
	.byte $ff,$0b
	.word @ref129
	.byte $ff,$0c
	.word @ref130
	.byte $ff,$0c
	.word @ref131
	.byte $ff,$0c
	.word @ref127
	.byte $ff,$0c
	.word @ref133
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref142:
	.byte $97
@ref143:
	.byte $97
@ref144:
	.byte $97
@ref145:
	.byte $97
@ref146:
	.byte $97
@ref147:
	.byte $97
@ref148:
	.byte $97
@ref149:
	.byte $93,$86,$4a,$00
@ref150:
	.byte $4c,$93,$00
@ref151:
	.byte $56,$83,$00,$52,$8b,$00
@ref152:
	.byte $4e,$8b,$00,$48,$85
@ref153:
	.byte $85,$00,$46,$87,$00,$4a,$00
@ref154:
	.byte $4c,$93,$00
	.byte $ff,$06
	.word @ref151
	.byte $ff,$05
	.word @ref152
@ref157:
	.byte $85,$00,$46,$8b,$00
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref158:
	.byte $97
@ref159:
	.byte $97
@ref160:
	.byte $97
@ref161:
	.byte $97
@ref162:
	.byte $97
@ref163:
	.byte $97
@ref164:
	.byte $97
@ref165:
	.byte $97
@ref166:
	.byte $97
@ref167:
	.byte $97
@ref168:
	.byte $97
@ref169:
	.byte $97
@ref170:
	.byte $97
@ref171:
	.byte $97
@ref172:
	.byte $97
@ref173:
	.byte $97
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref174:
	.byte $97
@ref175:
	.byte $97
@ref176:
	.byte $97
@ref177:
	.byte $97
@ref178:
	.byte $97
@ref179:
	.byte $97
@ref180:
	.byte $97
@ref181:
	.byte $97
@ref182:
	.byte $97
@ref183:
	.byte $97
@ref184:
	.byte $97
@ref185:
	.byte $97
@ref186:
	.byte $97
@ref187:
	.byte $97
@ref188:
	.byte $97
@ref189:
	.byte $97
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref190:
	.byte $f9,$85
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref191:
	.byte $f9,$85
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref192:
	.byte $f9,$85
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref193:
	.byte $f9,$85
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref194:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref195:
	.byte $f9,$85
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref196:
	.byte $f9,$85
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref197:
	.byte $f9,$85
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref198:
	.byte $f9,$85
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref199:
	.byte $f9,$85
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$08
@song5ch0loop:
@ref200:
	.byte $84,$57,$55,$51,$4d,$51,$46,$81
@ref201:
	.byte $4a,$83,$00,$42,$83,$00,$51,$54,$81
@ref202:
	.byte $56,$83,$00,$5a,$83,$00,$64,$83,$00
@ref203:
	.byte $5e,$93,$00
@ref204:
	.byte $57,$55,$51,$4d,$51,$46,$81
	.byte $ff,$09
	.word @ref201
@ref206:
	.byte $56,$83,$00,$54,$83,$00,$4c,$83,$00
@ref207:
	.byte $50,$93,$00
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@song5ch1loop:
@ref208:
	.byte $97
@ref209:
	.byte $97
@ref210:
	.byte $97
@ref211:
	.byte $97
@ref212:
	.byte $97
@ref213:
	.byte $97
@ref214:
	.byte $97
@ref215:
	.byte $97
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@song5ch2loop:
@ref216:
	.byte $84,$21,$2f,$41,$43,$47,$40,$00
@ref217:
	.byte $2b,$39,$4b,$51,$4b,$42,$81
@ref218:
	.byte $33,$35,$39,$3f,$43,$3c,$81
@ref219:
	.byte $3f,$3d,$39,$35,$39,$2e,$81
@ref220:
	.byte $21,$2f,$41,$43,$47,$40,$00
	.byte $ff,$07
	.word @ref217
	.byte $ff,$07
	.word @ref218
	.byte $ff,$07
	.word @ref220
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@song5ch3loop:
@ref224:
	.byte $97
@ref225:
	.byte $97
@ref226:
	.byte $97
@ref227:
	.byte $97
@ref228:
	.byte $97
@ref229:
	.byte $97
@ref230:
	.byte $97
@ref231:
	.byte $97
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@song5ch4loop:
@ref232:
	.byte $97
@ref233:
	.byte $97
@ref234:
	.byte $97
@ref235:
	.byte $97
@ref236:
	.byte $97
@ref237:
	.byte $97
@ref238:
	.byte $97
@ref239:
	.byte $97
	.byte $fd
	.word @song5ch4loop


@song6ch0:
	.byte $fb,$06
@song6ch0loop:
@ref240:
	.byte $f9,$85
	.byte $fd
	.word @song6ch0loop

@song6ch1:
@song6ch1loop:
@ref241:
	.byte $f9,$85
	.byte $fd
	.word @song6ch1loop

@song6ch2:
@song6ch2loop:
@ref242:
	.byte $f9,$85
	.byte $fd
	.word @song6ch2loop

@song6ch3:
@song6ch3loop:
@ref243:
	.byte $f9,$85
	.byte $fd
	.word @song6ch3loop

@song6ch4:
@song6ch4loop:
@ref244:
	.byte $f9,$85
	.byte $fd
	.word @song6ch4loop
