;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 5
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env0,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $23
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $33
	.word @env1,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ca,$c5,$c0,$00,$03
@env2:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c0,$00,$07
@env3:
	.byte $cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$07
@env4:
	.byte $cf,$cf,$ce,$cd,$cc,$cb,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0
	.byte $00,$0f


@song0ch0:
	.byte $fb,$0c
@song0ch0loop:
@ref0:
	.byte $82,$40,$83,$00,$59,$00,$4e,$8d,$00
@ref1:
	.byte $4a,$83,$00,$59,$00,$40,$8d,$00
@ref2:
	.byte $40,$83,$00,$4a,$83,$00,$59,$00,$5c,$85,$00
@ref3:
	.byte $58,$83,$00,$4e,$83,$00,$4a,$8b,$00
@ref4:
	.byte $40,$83,$00,$59,$00,$4e,$8d,$00
	.byte $ff,$08
	.word @ref1
	.byte $ff,$0b
	.word @ref2
	.byte $ff,$09
	.word @ref3
@ref8:
	.byte $9f
@ref9:
	.byte $9f
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref10:
	.byte $9f
@ref11:
	.byte $9f
@ref12:
	.byte $9f
@ref13:
	.byte $9f
@ref14:
	.byte $9f
@ref15:
	.byte $9f
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
@ref19:
	.byte $9f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref20:
	.byte $00,$9d
@ref21:
	.byte $00,$9d
@ref22:
	.byte $00,$9d
@ref23:
	.byte $00,$9d
@ref24:
	.byte $00,$9d
@ref25:
	.byte $00,$9d
@ref26:
	.byte $00,$9d
@ref27:
	.byte $00,$9d
@ref28:
	.byte $00,$9d
@ref29:
	.byte $00,$9d
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref30:
	.byte $81,$80,$14,$14,$00,$14,$14,$14,$00,$14,$15,$00,$14,$15,$00
@ref31:
	.byte $81,$14,$14,$00,$14,$14,$14,$00,$14,$15,$00,$14,$15,$00
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $ff,$0e
	.word @ref31
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref40:
	.byte $9f
@ref41:
	.byte $9f
@ref42:
	.byte $9f
@ref43:
	.byte $9f
@ref44:
	.byte $9f
@ref45:
	.byte $9f
@ref46:
	.byte $9f
@ref47:
	.byte $9f
@ref48:
	.byte $9f
@ref49:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$07
@song1ch0loop:
@ref50:
	.byte $82,$4a,$00,$83,$52,$00,$83,$40,$00,$83,$52,$00,$83
@ref51:
	.byte $4a,$00,$83,$52,$00,$83,$40,$00,$83,$52,$00,$83
	.byte $ff,$0c
	.word @ref51
	.byte $ff,$0c
	.word @ref51
	.byte $ff,$0c
	.word @ref51
@ref55:
	.byte $4e,$00,$83,$58,$00,$83,$40,$00,$83,$58,$00,$83
	.byte $ff,$0c
	.word @ref51
@ref57:
	.byte $3c,$00,$83,$4a,$00,$83,$4e,$00,$83,$58,$00,$83
	.byte $ff,$0c
	.word @ref51
	.byte $ff,$0c
	.word @ref57
@ref60:
	.byte $3c,$00,$83,$4a,$00,$83,$40,$00,$83,$48,$00,$83
@ref61:
	.byte $4a,$00,$9b
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref62:
	.byte $9f
@ref63:
	.byte $9f
@ref64:
	.byte $9f
@ref65:
	.byte $9f
@ref66:
	.byte $82,$52,$83,$00,$83,$55,$58,$83,$00,$87
@ref67:
	.byte $54,$83,$00,$55,$59,$00,$85,$40,$85
@ref68:
	.byte $52,$83,$00,$83,$55,$58,$85,$62,$85
@ref69:
	.byte $5c,$8d,$58,$8d
@ref70:
	.byte $52,$83,$00,$83,$55,$58,$83,$00,$87
	.byte $ff,$09
	.word @ref67
@ref72:
	.byte $52,$83,$00,$53,$55,$4e,$85,$00,$85
@ref73:
	.byte $9f
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref74:
	.byte $00,$9d
@ref75:
	.byte $00,$9d
@ref76:
	.byte $00,$9d
@ref77:
	.byte $00,$9d
@ref78:
	.byte $00,$9d
@ref79:
	.byte $00,$9d
@ref80:
	.byte $00,$9d
@ref81:
	.byte $00,$9d
@ref82:
	.byte $00,$9d
@ref83:
	.byte $00,$9d
@ref84:
	.byte $00,$9d
@ref85:
	.byte $00,$9d
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref86:
	.byte $9f
@ref87:
	.byte $9f
@ref88:
	.byte $9f
@ref89:
	.byte $9f
@ref90:
	.byte $9f
@ref91:
	.byte $9f
@ref92:
	.byte $9f
@ref93:
	.byte $9f
@ref94:
	.byte $9f
@ref95:
	.byte $9f
@ref96:
	.byte $9f
@ref97:
	.byte $9f
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref98:
	.byte $9f
@ref99:
	.byte $9f
@ref100:
	.byte $9f
@ref101:
	.byte $9f
@ref102:
	.byte $9f
@ref103:
	.byte $9f
@ref104:
	.byte $9f
@ref105:
	.byte $9f
@ref106:
	.byte $9f
@ref107:
	.byte $9f
@ref108:
	.byte $9f
@ref109:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$09
@song2ch0loop:
@ref110:
	.byte $86,$56,$00,$4c,$00,$56,$00,$4c,$00,$56,$00,$4c,$00
@ref111:
	.byte $56,$00,$4c,$00,$56,$00,$4c,$00,$56,$00,$4c,$00
@ref112:
	.byte $48,$00,$44,$00,$4c,$83,$00,$44,$00,$48,$00
@ref113:
	.byte $52,$00,$50,$00,$52,$00,$56,$00,$50,$00,$48,$00
@ref114:
	.byte $56,$00,$48,$00,$56,$00,$48,$00,$56,$00,$48,$00
@ref115:
	.byte $56,$00,$46,$00,$56,$00,$46,$00,$58,$83,$00
@ref116:
	.byte $56,$00,$4e,$00,$56,$00,$4e,$00,$52,$00,$56,$00
@ref117:
	.byte $52,$83,$00,$4e,$83,$00,$4a,$83,$00
	.byte $ff,$0c
	.word @ref111
	.byte $ff,$0c
	.word @ref111
	.byte $ff,$0b
	.word @ref112
	.byte $ff,$0c
	.word @ref113
	.byte $ff,$0c
	.word @ref114
	.byte $ff,$0b
	.word @ref115
	.byte $ff,$0c
	.word @ref116
	.byte $ff,$09
	.word @ref117
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref126:
	.byte $86,$3e,$00,$44,$00,$4c,$00,$44,$00,$4c,$00,$44,$00
@ref127:
	.byte $3e,$00,$44,$00,$4c,$00,$44,$00,$4c,$00,$44,$00
@ref128:
	.byte $36,$00,$3e,$00,$44,$00,$3e,$00,$36,$00,$3e,$00
@ref129:
	.byte $36,$00,$3e,$00,$44,$00,$3e,$83,$00,$36,$00
@ref130:
	.byte $30,$00,$36,$00,$3e,$00,$36,$00,$3e,$00,$36,$00
@ref131:
	.byte $30,$00,$34,$00,$3e,$00,$34,$00,$3e,$00,$34,$00
	.byte $ff,$0c
	.word @ref127
@ref133:
	.byte $3a,$00,$40,$00,$4c,$00,$40,$00,$4c,$00,$40,$00
	.byte $ff,$0c
	.word @ref127
	.byte $ff,$0c
	.word @ref127
	.byte $ff,$0c
	.word @ref128
	.byte $ff,$0b
	.word @ref129
	.byte $ff,$0c
	.word @ref130
	.byte $ff,$0c
	.word @ref131
	.byte $ff,$0c
	.word @ref127
	.byte $ff,$0c
	.word @ref133
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref142:
	.byte $00,$95
@ref143:
	.byte $00,$95
@ref144:
	.byte $00,$95
@ref145:
	.byte $00,$95
@ref146:
	.byte $00,$95
@ref147:
	.byte $00,$95
@ref148:
	.byte $00,$95
@ref149:
	.byte $93,$86,$4a,$00
@ref150:
	.byte $4c,$93,$00
@ref151:
	.byte $56,$83,$00,$52,$8b,$00
@ref152:
	.byte $4e,$8b,$00,$48,$85
@ref153:
	.byte $85,$00,$46,$87,$00,$4a,$00
@ref154:
	.byte $4c,$93,$00
	.byte $ff,$06
	.word @ref151
	.byte $ff,$05
	.word @ref152
@ref157:
	.byte $85,$00,$46,$8b,$00
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref158:
	.byte $97
@ref159:
	.byte $97
@ref160:
	.byte $97
@ref161:
	.byte $97
@ref162:
	.byte $97
@ref163:
	.byte $97
@ref164:
	.byte $97
@ref165:
	.byte $97
@ref166:
	.byte $97
@ref167:
	.byte $97
@ref168:
	.byte $97
@ref169:
	.byte $97
@ref170:
	.byte $97
@ref171:
	.byte $97
@ref172:
	.byte $97
@ref173:
	.byte $97
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref174:
	.byte $97
@ref175:
	.byte $97
@ref176:
	.byte $97
@ref177:
	.byte $97
@ref178:
	.byte $97
@ref179:
	.byte $97
@ref180:
	.byte $97
@ref181:
	.byte $97
@ref182:
	.byte $97
@ref183:
	.byte $97
@ref184:
	.byte $97
@ref185:
	.byte $97
@ref186:
	.byte $97
@ref187:
	.byte $97
@ref188:
	.byte $97
@ref189:
	.byte $97
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$07
@song3ch0loop:
@ref190:
	.byte $86,$43,$51,$48,$85,$47,$48,$81
@ref191:
	.byte $4c,$91,$3e,$81
@ref192:
	.byte $43,$51,$48,$85,$47,$48,$81
@ref193:
	.byte $4c,$95
	.byte $ff,$07
	.word @ref192
@ref195:
	.byte $4c,$91,$3e,$81
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref196:
	.byte $97
@ref197:
	.byte $97
@ref198:
	.byte $97
@ref199:
	.byte $87,$86,$55,$57,$54,$56,$54,$4c
@ref200:
	.byte $50,$89,$5a,$85,$60,$81
@ref201:
	.byte $5a,$95
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref202:
	.byte $00,$95
@ref203:
	.byte $00,$95
@ref204:
	.byte $00,$95
@ref205:
	.byte $00,$95
@ref206:
	.byte $00,$95
@ref207:
	.byte $00,$95
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref208:
	.byte $97
@ref209:
	.byte $97
@ref210:
	.byte $97
@ref211:
	.byte $97
@ref212:
	.byte $97
@ref213:
	.byte $97
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref214:
	.byte $97
@ref215:
	.byte $97
@ref216:
	.byte $97
@ref217:
	.byte $97
@ref218:
	.byte $97
@ref219:
	.byte $97
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$05
@song4ch0loop:
@ref220:
	.byte $87,$86,$54,$89,$54,$89
@ref221:
	.byte $50,$85,$51,$50,$91
@ref222:
	.byte $87,$54,$89,$54,$89
@ref223:
	.byte $54,$89,$52,$85,$4f,$4a,$85
	.byte $ff,$05
	.word @ref222
	.byte $ff,$05
	.word @ref221
@ref226:
	.byte $58,$89,$5c,$91
@ref227:
	.byte $54,$85,$55,$54,$91
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref228:
	.byte $87,$86,$44,$89,$44,$89
@ref229:
	.byte $46,$85,$47,$46,$91
@ref230:
	.byte $87,$44,$89,$44,$89
@ref231:
	.byte $40,$89,$40,$91
	.byte $ff,$05
	.word @ref230
	.byte $ff,$05
	.word @ref229
@ref234:
	.byte $4a,$89,$4a,$91
@ref235:
	.byte $5c,$85,$5f,$62,$91
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref236:
	.byte $86,$40,$00,$40,$00,$58,$00,$40,$00,$58,$00,$83,$58,$00,$40,$00
@ref237:
	.byte $3a,$85,$50,$00,$3a,$00,$83,$3a,$00,$50,$00,$3a,$00
@ref238:
	.byte $40,$00,$40,$00,$58,$00,$40,$00,$58,$00,$83,$58,$00,$40,$00
@ref239:
	.byte $44,$83,$00,$5c,$00,$44,$87,$00,$5c,$83,$00
	.byte $ff,$0f
	.word @ref238
	.byte $ff,$0d
	.word @ref237
@ref242:
	.byte $4a,$83,$00,$58,$00,$44,$00,$58,$00,$44,$00,$58,$00,$44,$00
@ref243:
	.byte $4a,$83,$00,$58,$00,$62,$83,$00,$54,$00,$62,$00,$54,$00
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref244:
	.byte $80,$09,$88,$05,$80,$0d,$88,$0b,$80,$17,$09,$05,$10,$81
@ref245:
	.byte $09,$88,$05,$80,$0d,$88,$0b,$80,$17,$09,$05,$10,$81
	.byte $ff,$09
	.word @ref245
	.byte $ff,$09
	.word @ref245
	.byte $ff,$09
	.word @ref245
	.byte $ff,$09
	.word @ref245
	.byte $ff,$09
	.word @ref245
	.byte $ff,$09
	.word @ref245
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref252:
	.byte $9f
@ref253:
	.byte $9f
@ref254:
	.byte $9f
@ref255:
	.byte $9f
@ref256:
	.byte $9f
@ref257:
	.byte $9f
@ref258:
	.byte $9f
@ref259:
	.byte $9f
	.byte $fd
	.word @song4ch4loop
